name: Upload to PyPI

on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags') &&
      github.ref == 'refs/heads/main'
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          # Upgrade pip, setuptools, wheel, and build
          python -m pip install --upgrade pip setuptools wheel build
      - name: Build package
        run: python -m build
      - name: Upload the distribution files
        uses: actions/upload-artifact@v3
        with:
          path: ./dist
  publish:
    needs: build
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      # IMPORTANT: This permission is mandatory for trusted publishing
      id-token: write
    steps:
    - name: Download the distribution files
      uses: actions/download-artifact@v3
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: artifact/
