name: Upload release to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        # Upgrade pip, setuptools, wheel, and build
        run: python -m pip install --upgrade pip setuptools wheel build
      - name: Build package
        run: python -m build
      - name: Upload the distribution files
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      # IMPORTANT: This permission is mandatory for trusted publishing
      id-token: write
    steps:
    - name: Download the distribution files
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist/
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      